### ISSUE TITLE
Infinite loop in read_images_stage5.open_reference?

### ISSUE THREAD

**Issue by rachel3834** [pyDANDIA/pyDANDIA#59] opened 2018-06-29 16:33 UTC
I am running a reduction of the ROME-FIELD-03 SDSS-g data so far, and the reduction has reached stage 5 but seems to be stuck at the point of reading in the reference image.  The last entry in the log reads:

2018-06-29T04:54:17 Attempting to open ref image /data01/rstreet/data_reduction/proc/ROME-FIELD-03_lsc-doma-1m0-05-fl15_gp/ref/lsc1m005-fl15-20170825-0095-e91.fits

Its now 2018-06-29T16:31:22 and this process is still running - it has one CPU maxed out at 100%.  

Comparing this with reductions of other data I see this step in the pipeline typically takes ~1hr for a fullframe.

**Comment by mpgh** [comment] 2018-06-29 16:55
I can't reproduce that. Have you pulled today? Perhaps one of the changes affects the single image processing....

**Comment by rachel3834** [comment] 2018-06-29 17:31
No - Etienne has just explained this may well be fixed in the most up to date version.  I will update and re-test.

**Comment by ytsapras** [comment] 2019-02-07 16:55
Closing this since s5 operates fine.

**Closed by ytsapras** 2019-02-07 16:55 UTC
